- block:
    - include_tasks: sync-dns.yml
      loop: "{{ MIKROTIK_HOSTS }}"
  module_defaults:
    group/community.routeros.api:
      password: "{{ MIKROTIK_PASSWORD }}"
      username: "{{ MIKROTIK_USERNAME }}"
      hostname: "{{ item }}"