- block:
    - include_tasks: disable-ipv6.yml
      loop: "{{ MIKROTIK_HOSTS }}"
    - include_tasks: disable-mac-server.yml
      loop: "{{ MIKROTIK_HOSTS }}"
    - include_tasks: disable-services.yml
      loop: "{{ MIKROTIK_HOSTS }}"
  module_defaults:
    group/community.routeros.api:
      password: "{{ MIKROTIK_PASSWORD }}"
      username: "{{ MIKROTIK_USERNAME }}"
      hostname: "{{ item }}"